#
# ░█▀▀█ ▒█▄░▒█ ▀▀█▀▀ ▀█▀ ░░ ▒█▀▀█ ▒█░▒█ ▒█▀▀▀█ ▒█▀▀█ 　 ▒█▀▀▀█ ▒█░░▒█ ▒█▀▀▀█ ▀▀█▀▀ ▒█▀▀▀ ▒█▀▄▀█
# ▒█▄▄█ ▒█▒█▒█ ░▒█░░ ▒█░ ▀▀ ▒█▀▀▄ ▒█▀▀█ ▒█░░▒█ ▒█▄▄█ 　 ░▀▀▀▄▄ ▒█▄▄▄█ ░▀▀▀▄▄ ░▒█░░ ▒█▀▀▀ ▒█▒█▒█
# ▒█░▒█ ▒█░░▀█ ░▒█░░ ▄█▄ ░░ ▒█▄▄█ ▒█░▒█ ▒█▄▄▄█ ▒█░░░ 　 ▒█▄▄▄█ ░░▒█░░ ▒█▄▄▄█ ░▒█░░ ▒█▄▄▄ ▒█░░▒█
#

# Эффект при отмене прыжка. true/false
Effect: true
# Длительность эффекта в секундах
Effect-dealy: 3

# Сообщение на экране
Title: "&cERROR"
Subtitle: "&fБанихоп запрещён&c!"

# Сообщение над быстрыми слотами
Action-bar: "&fИзвините, банихоп &cзапрещён"

# Сообщение о перезагрузке конфига
Reload: "&a| &fКонфигурация плагина, успешно перезагружена"

# Сообщение если ввели /abh без аргумента reload
Usage: "&c| &fИспользуйте: &e/abh help"

# Сообщение при вводе неизвестной команды
Unknown: "&c| &fИзвините, такой команды &cне&f существует"

# Сообщение при недостатке прав на команду
Permission: "&c| &fНедостаточно прав"

# /abh enable - message
Enable title: "&cSystem alert"
Enable subtitle: "&fСистема включена"

Error enable title: "&cSystem alert"
Error enable subtitle: "&fСистема уже включена"

# /abh disable - message
Disable title: "&cSystem alert"
Disable subtitle: "&fСистема отключена"

Error disable title: "&cSystem alert"
Error disable subtitle: "&fСистема уже отключена"
