#
# ░█▀▀█ ▒█▄░▒█ ▀▀█▀▀ ▀█▀ ░░ ▒█▀▀█ ▒█░▒█ ▒█▀▀▀█ ▒█▀▀█ 　 ▒█▀▀▀█ ▒█░░▒█ ▒█▀▀▀█ ▀▀█▀▀ ▒█▀▀▀ ▒█▀▄▀█
# ▒█▄▄█ ▒█▒█▒█ ░▒█░░ ▒█░ ▀▀ ▒█▀▀▄ ▒█▀▀█ ▒█░░▒█ ▒█▄▄█ 　 ░▀▀▀▄▄ ▒█▄▄▄█ ░▀▀▀▄▄ ░▒█░░ ▒█▀▀▀ ▒█▒█▒█
# ▒█░▒█ ▒█░░▀█ ░▒█░░ ▄█▄ ░░ ▒█▄▄█ ▒█░▒█ ▒█▄▄▄█ ▒█░░░ 　 ▒█▄▄▄█ ░░▒█░░ ▒█▄▄▄█ ░▒█░░ ▒█▄▄▄ ▒█░░▒█
#

# Эффект при отмене прыжка. true/false
Effect: true
# Длительность эффекта в секундах
Effect-dealy: 3

# Сообщение на экране
Title: "&cERROR"
Subtitle: "&fБанихоп запрещён&c!"
Action-bar: "&fИзвините, банихоп &cзапрещён" # Над слотами

# Сообщения в чате
Reload: "&a| &fКонфигурация плагина, успешно перезагружена"
Usage: "&c| &fИспользуйте: &e/abh help"
Unknown: "&c| &fИзвините, такой команды &cне&f существует"
Permission: "&c| &fНедостаточно прав"

# /abh enable - message
Enable title: "&cSystem alert"
Enable subtitle: "&fСистема включена"

Error enable title: "&cSystem alert"
Error enable subtitle: "&fСистема уже включена"

# /abh disable - message
Disable title: "&cSystem alert"
Disable subtitle: "&fСистема отключена"

Error disable title: "&cSystem alert"
Error disable subtitle: "&fСистема уже отключена"
