name: AntiBHOP
version: 1.3.1
main: org.harakiry.AntiBHOP
api-version: '1.16'
authors: [Ght]
description: RP Control bhop
commands:
  abh:
    usage: /<command>
    description: Reload configuration plugin